micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3306/micronaut_db
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true
      url: jdbc:mysql://127.0.0.1:3306/micronaut_db
      username: root
      password: password