micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:micronaut_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true