name: micronaut-crud CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: micronaut_db
          MYSQL_USER: micronaut_user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Use Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Use Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Verify MySQL connection
        run: |
          sudo apt-get install -y mysql-client
          mysql --protocol=tcp -h 127.0.0.1 -u micronaut_user -ppassword -e "SHOW DATABASES;"

      - name: Verify MySQL Connection Before Flyway
        run: |
          mysql -h 127.0.0.1 -u micronaut_user -ppassword -e "USE micronaut_db;"

      - name: Ensure MySQL User Has Correct Permissions
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "
          GRANT ALL PRIVILEGES ON micronaut_db.* TO 'micronaut_user'@'%';
          FLUSH PRIVILEGES;"

      - name: Build and Apply Flyway Migrations
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: micronaut_db
          DB_USER: root
          DB_PASSWORD: password
        run: |
          echo "=== Printing Environment Variables ==="
          echo "DB_HOST: $DB_HOST"
          echo "DB_PORT: $DB_PORT"
          echo "DB_NAME: $DB_NAME"
          echo "DB_USER: $DB_USER"
          echo "DB_PASSWORD: $DB_PASSWORD"
  
          echo "=== Running Flyway Migration ==="
            ./gradlew flywayMigrate --stacktrace

      - name: Build and Test Application
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: password
        run: |
          ./gradlew clean build
          ./gradlew test