name: micronaut-crud CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: micronaut_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Use Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Use Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Verify MySQL connection
        run: |
          sudo apt-get install -y mysql-client
          mysql --protocol=tcp -h 127.0.0.1 -u root -ppassword -e "SHOW DATABASES;"

      - name: Build and Test Application
        run: |
          ./gradlew clean build --stacktrace

      - name: Check if db exist
        run: |
          TABLE_EXISTS=$(mysql -h 127.0.0.1 -u root -ppassword -D micronaut_db -N -B -e \
          "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='micronaut_db' AND table_name='books';")
        
          if [ "$TABLE_EXISTS" -eq "1" ]; then
          echo "Table 'books' exists."
          else
          echo "Table 'books' does NOT exist."
          exit 1
          fi

