name: micronaut-crud CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: micronaut_db
          MYSQL_USER: micronaut_user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Use Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Use Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Create `books` Table in MySQL
        run: |
          mysql -h 127.0.0.1 -u micronaut_user -ppassword micronaut_db -e "
          CREATE TABLE books (
            id BIGINT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            author VARCHAR(255) NOT NULL,
            price DOUBLE NOT NULL,
            total_page INT NOT NULL
          );"

      - name: Build and Test Application
        env:
          DB_HOST: 127.0.0.1
          DB_USER: micronaut_user
          DB_PASSWORD: password
        run: |
          ./gradlew build
          ./gradlew test

      - name: Print Gradle Problem Report
        if: failure()
        run: cat build/reports/problems/problems-report.html || true
